Changed line 32, const  uint& y to const  uint32_t& y due to ISO C++ error
Error was:

in file included from ./drizzled/session.h:172,
                 from drizzled/table_proto_write.cc:18:
 ./drizzled/lex_column.h:32: error: expected ',' or '...' before '&' token
 ./drizzled/lex_column.h:32: error: ISO C++ forbids declaration of 'uint'
 with no type
 ./drizzled/lex_column.h: In constructor
 'drizzled::Lex_Column::Lex_Column(const drizzled::String&, int)':
 ./drizzled/lex_column.h:32: error: 'y' was not declared in this scope