fix large stack usage in logging_gearman:
use a auto_ptr for the buffer (which was 32k itself).

plugin/logging_gearman/logging_gearman.cc: In member function virtual bool LoggingGearman::post(drizzled::Session*):
plugin/logging_gearman/logging_gearman.cc:292: error: the frame size of 33216 bytes is larger than 32768 bytes [-Wframe-larger-than=]